package io.github.pigaut.yaml.node.line;

public enum LineStyle {

    LABELED,   // key: label value1, value2, etc... key1=value1 key2=value2 etc...
    COMMA,     // key: value1, value2, etc... key1=value1 key2=value2 etc...
    SPACED;    // key: value1 value2 etc... key1=value1 key2=value2 etc...

}
