package io.github.pigaut.yaml.node.line;

public enum LineStyle {

    LABELED,   // label value1, value2, etc... key1=value1 key2=value2 etc...
    COMMA,     // value1, value2, etc... key1=value1 key2=value2 etc...
    COLON,     // value1:value2:etc...  key1=value1 key2=value2 etc...
    SPACED;    // value1 value2 etc... key1=value1 key2=value2 etc...

}
